version: '3.8'

services:
  flask-shortener-backend:
    container_name: fus_url
    build: ./
    working_dir: /usr/src/final_url
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 'true'
      FLASK_ENV: development
    links:
      - redis
      - db
    networks:
      - default
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/final_url

  redis:
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"
  db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'url_shortener_1_0_0'
        MYSQL_USER: 'mysql'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - my-db:/var/lib/mysql

networks:
  default:

volumes:
  my-db: